name: Test with Nondex
run-name: Known Flaky test
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: 
          mvn -pl pinot-common test -Dtest=org.apache.pinot.queries.ExplainPlanQueriesTest.testSelectAggregateUsingFilterIndexGroupByVerbose
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: 
          mvn -pl pinot-common edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.pinot.queries.ExplainPlanQueriesTest.testSelectAggregateUsingFilterIndexGroupByVerbose
